name: Flutter CI

on:
  push:
    branches:
      - master  # Workflow ini akan dijalankan saat ada perubahan (push) ke branch 'master'
  pull_request:
    branches:
      - master  # Workflow juga akan dijalankan untuk pull request ke branch 'master'

jobs:
  build:
    runs-on: ubuntu-latest  # Menggunakan runner Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout kode sumber dari repository

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Menginstal Flutter SDK
        with:
          flutter-version: 'stable'  # Menggunakan versi stabil Flutter

      - name: Install dependencies
        run: flutter pub get  # Mengunduh dependensi yang terdaftar di pubspec.yaml

      - name: Run tests
        run: flutter test  # Menjalankan tes unit dan widget

      - name: Build APK
        run: flutter build apk --release  # Membangun APK aplikasi Flutter untuk rilis
